name: Linting Pull Pequest

on:
  pull_request:
    branches:
      - develop

jobs:
  lint-run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2

        with:
          node-version: '14'

      - name: Install dependencies

        run: cd front-citatheque && npm  ci

      - name: Lint code

        run: cd front-citatheque && npm run lint --fix